### ISSUE TITLE
Useraccounts: Partition-wise configuration and secondary groups

### ISSUE THREAD

**Issue by staeglis** [OleHolmNielsen/Slurm_tools#2]
Dear Ole,

thank you for providing your scripts. There will be very helpful for me.

But I've two questions:
1. I can't define partition-wise values. But it should be possible to maintain this directly via sacctmgr?
2. The script doesn't evaluates secondary group memberships?

Kind regards,
Stefan

**Comment by OleHolmNielsen** [comment]
Hi Stefan,
Thanks for your questions. I think I haven't considered the questions which you rise. Admittedly, the scripts are a little simple and don't do more sophisticated things which you would like to do.
For us the scripts work well for what we need to do, except perhaps when a user changes his UNIX GID. I haven't had the time to think thorough this task yet.
Best regards,
Ole

**Comment by jakerundall** [comment]
Have you given any more thought to the ability to set partition-specific settings via the slurmusersettings script? In your SLUG presentation you mentioned that the script (and config file) could potentially be generalized to support complete Slurm associations (username:cluster:partition:account). And indeed I see a few lines in the script where a step may have been taken in that direction:
```
        # [DEFAULT|NEWUSER|UNIX_group|username]:[Type]:value[:partition[:cluster]]
...
        # The partition and cluster fields (4,5) are optional, defaults are chosen if omitted.
```
But I don't think this is fully implemented (specifying a 'partition' doesn't seem to have any effect, anyway), nor does that suggested syntax seem to indicate it would be possible to specify an account (only user + optional partition + potentially a cluster as well).

**Comment by OleHolmNielsen** [comment]
Hi Jake, thanks for your interest. I didn't have time to look at the generalization which you refer to, since we don't seem to have a strong case for this functionality at our site. Adding partition and cluster dimensions to all the Awk arrays in the script I estimate as quite a lot of work, plus testing of the logic which can be a bit complex in places. So unfortunately I have to disappoint you for now.

**Comment by jakerundall** [comment]
That's understandable. We might be interested in using your code as a starting point for something that would provide that functionality. I'm hesitant to suggest that we'd simply be adding that functionality, however, because we might end up dropping some features (as you point out, testing all of the logic can be complex) or altering some.

Would that be OK with you? I'm not sure I'd literally fork the repo because I don't think we need to maintain the complete collection of the other tools contained here (which seem very interesting indeed). But as I say we might like to reuse major portions of the slurmaccounts/slurmusersettings tools in particular.

**Comment by OleHolmNielsen** [comment]
I'm OK with sharing my code in the true Open Source spirit, where you are welcome to use my code if you promise to make your new tools publicly available as well. We need good Slurm administration tools, so I look forward to testing your new code!
BTW, what is your affiliation?

**Comment by jakerundall** [comment]
Thanks, I'm at NCSA at the University of Illinois in the US.

If we do end up using the code as a starting point I'd be happy to post the result on GitHub as you've done. In that case, I'm hearing guidance from my colleagues that it would be best if I were able to put an actual open source license on such code.

Evidently w/o such a license the code officially remains under default copyright, e.g., see GitHub's own guidance:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

Our work at NCSA has a variety of funding sources and some of them require open source licenses on code that is made publicly available.

Would it be OK with you for us to use such a license on any derivative work we create? That would enable things on our end.

One option/facilitator here might be for you to add an open-source license on this repository. Such a license would generally indicate conditions for creating derivative works (sometimes indicating requirements that the same license has to be attached to such work).

**Comment by OleHolmNielsen** [comment]
Would the GNU General Public License v3.0 at https://choosealicense.com/licenses/gpl-3.0/ be suitable for NCSA?  My colleagues have an Open Source project under this license, so I should probably follow suit.  I could apply this license to my Slurm_tools project, including the tools which you are interested in.

**Comment by jakerundall** [comment]
I don't have much knowledge about/experience with software licensing. Some of my developer colleagues have advised that they avoid use of GPL3 because many of their external collaborators aren't comfortable with it. They usually recommend and prefer the MIT license. But based on a little bit of my own research I don't see any reason that GPL would actually cause any issues on my end. And it's your call, of course. Thanks!

**Comment by OleHolmNielsen** [comment]
Thanks for sharing your insights. I have added the GPL3 license file to the project top, based upon my colleagues' use of that license for other projects.

**Comment by jakerundall** [comment]
Great, thank you!
